apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: device-registry
  description: provides device registration capability
  tags:
    - java
    - quarkus 
spec:
  type: service
  lifecycle: production
  owner: arvind-demo-team
  system: bobbycar
  dependsOn:
    - resource:amq-broker