apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: device-registry
  description: provides device registration capability
  tags:
    - java
    - quarkus
  links:
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?devfilePath=.devfilev2-theia.yaml
      title: OpenShift Dev Spaces (Eclipse Theia)
      icon: web
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web         
spec:
  type: service
  lifecycle: production
  owner: arvind-demo-team
  system: bobbycar
  dependsOn:
    - resource:amq-broker