apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka2datagrid
  description: caches messages coming from kafka
  tags:
    - java
    - kamelk 
spec:
  type: kafka-streams
  lifecycle: production
  owner: arvind-demo-team
  system: bobbycar
  dependsOn:
    - resource:amq-streams