apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bc-telemetry-aggregator
  description: aggreates telemetry from kafka
  tags:
    - java
    - quarkus
  annotations:
    'sonarqube.org/project-key': raffaelespazzoli_bc-telemetry-aggregator
  links:
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?devfilePath=.devfilev2-theia.yaml
      title: OpenShift Dev Spaces (Eclipse Theia)
      icon: web
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: kafka-streams
  lifecycle: production
  owner: arvind-demo-team
  system: bobbycar
  dependsOn:
    - resource:amq-streams
