apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bc-telemetry-aggregator
  description: aggreates telemetry from kafka
  tags:
    - java
    - quarkus
  annotations: 
    'sonarqube.org/project-key': raffaelespazzoli_bc-telemetry-aggregator
spec:
  type: kafka-streams
  lifecycle: production
  owner: arvind-demo-team
  system: bobbycar
  dependsOn:
    - resource:amq-streams
