apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: amq-streams
  description: amq-streams
  links:
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?devfilePath=.devfilev2-theia.yaml
      title: CodeReady Workspaces (Eclipse Theia)
      icon: web
    - url: https://eclipse-che.apps.control-cluster-raffa.demo.red-chesterfield.com/#https://github.com/raf-backstage-demo/raffa-qrs2?che-editor=che-incubator/che-code/insiders&devfilePath=.devfilev2-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web      
spec:
  type: kafka
  owner: arvind-demo-team
  system: bobbycar